server:
  port: 8000

spring:
  datasource:
    url: jdbc:postgresql://localhost:5315/filestoredb
    username: postgresuser
    password: postgrespassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update